"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23 18:52:31.920876
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=False),
        sa.Column("psid", sa.String(length=64), nullable=False),
        sa.Column("user_ref", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_user_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_bot_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_disclosure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fallback_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handoff_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("handoff_reason", sa.String(length=64), nullable=True),
        sa.Column("handoff_by", sa.String(length=64), nullable=True),
        sa.Column("handoff_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bot_resumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto_seq", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_pending_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_id", "psid", name="uq_conversations_page_psid"),
    )
    op.create_index(
        "ix_conversations_next_run_at",
        "conversations",
        ["next_run_at"],
        unique=False,
        postgresql_where=sa.text("next_run_at IS NOT NULL"),
    )
    op.create_index(op.f("ix_conversations_user_ref"), "conversations", ["user_ref"], unique=False)
    op.create_table(
        "dataset_exports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("num_samples", sa.Integer(), nullable=False),
        sa.Column("candidate_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default=sa.text("'sft'"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=True),
        sa.Column("outcome", sa.String(length=96), nullable=True),
        sa.Column("latest_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("graph_thread_id", sa.String(length=128), nullable=True),
        sa.Column("checkpoint_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("adapter_version", sa.String(length=128), nullable=True),
        sa.Column("model_latency_ms", sa.Integer(), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("check_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("draft_text", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_turns_conv_created", "turns", ["conversation_id", "created_at"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.String(length=8), nullable=True),
        sa.Column("corrected_reply", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_turn_id"), "feedback", ["turn_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=24), server_default=sa.text("'text'"), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("attachment_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mid", sa.String(length=255), nullable=True),
        sa.Column("event_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("allow_during_handoff", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("send_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("echo_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_conv_seq", "messages", ["conversation_id", "id"], unique=False)
    op.create_index(
        "ix_messages_conv_status", "messages", ["conversation_id", "role", "status"], unique=False
    )
    op.create_index(op.f("ix_messages_turn_id"), "messages", ["turn_id"], unique=False)
    op.create_index(
        "uq_messages_idempotency_key",
        "messages",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "uq_messages_mid", "messages", ["mid"], unique=True, postgresql_where=sa.text("mid IS NOT NULL")
    )
    op.create_table(
        "training_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("sample", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rejected_reply", sa.Text(), nullable=True),
        sa.Column("pii_redacted", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "pii_detected_before_redaction", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("usage_rights_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reviewer", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("exported_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_candidates_conversation_id"),
        "training_candidates",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_training_candidates_status"), "training_candidates", ["status"], unique=False)
    op.create_index(op.f("ix_training_candidates_turn_id"), "training_candidates", ["turn_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_candidates_turn_id"), table_name="training_candidates")
    op.drop_index(op.f("ix_training_candidates_status"), table_name="training_candidates")
    op.drop_index(op.f("ix_training_candidates_conversation_id"), table_name="training_candidates")
    op.drop_table("training_candidates")
    op.drop_index("uq_messages_mid", table_name="messages", postgresql_where=sa.text("mid IS NOT NULL"))
    op.drop_index(
        "uq_messages_idempotency_key",
        table_name="messages",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_messages_turn_id"), table_name="messages")
    op.drop_index("ix_messages_conv_status", table_name="messages")
    op.drop_index("ix_messages_conv_seq", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_feedback_turn_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("ix_turns_conv_created", table_name="turns")
    op.drop_table("turns")
    op.drop_table("worker_heartbeats")
    op.drop_table("dataset_exports")
    op.drop_index(op.f("ix_conversations_user_ref"), table_name="conversations")
    op.drop_index(
        "ix_conversations_next_run_at",
        table_name="conversations",
        postgresql_where=sa.text("next_run_at IS NOT NULL"),
    )
    op.drop_table("conversations")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
